### ISSUE TITLE
Argument for @NotNull parameter 'repository' of git4idea/branch/GitBranchUtil.getBranchNameOrRev must not be null

### ISSUE THREAD

**Issue by ragol** [OpherV/gitflow4idea#117]
_Cloned from https://youtrack.jetbrains.com/issue/IDEA-160123_

I work on a project that is managed by Mercurial. I configured a Jira instance as Task Server. When switching to task, that does not have an icon before its name, nothing happens. Switching to a task with an icon works as expected.

In the log file I see the following:

```
2016-08-22 12:17:22,413 [ 228156]  ERROR - pplication.impl.LaterInvocator - PhpStorm 2016.2.1  Build #PS-162.1628.23 
2016-08-22 12:17:22,413 [ 228156]  ERROR - pplication.impl.LaterInvocator - JDK: 1.8.0_76-release 
2016-08-22 12:17:22,413 [ 228156]  ERROR - pplication.impl.LaterInvocator - VM: OpenJDK 64-Bit Server VM 
2016-08-22 12:17:22,413 [ 228156]  ERROR - pplication.impl.LaterInvocator - Vendor: JetBrains s.r.o 
2016-08-22 12:17:22,413 [ 228156]  ERROR - pplication.impl.LaterInvocator - OS: Linux 
2016-08-22 12:17:22,413 [ 228156]  ERROR - pplication.impl.LaterInvocator - Last Action: tasks.goto 
2016-08-22 12:17:47,703 [ 253446]  ERROR - pplication.impl.LaterInvocator - Argument for @NotNull parameter 'repository' of git4idea/branch/GitBranchUtil.getBranchNameOrRev must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'repository' of git4idea/branch/GitBranchUtil.getBranchNameOrRev must not be null
        at git4idea.branch.GitBranchUtil.getBranchNameOrRev(GitBranchUtil.java)
        at gitflow.GitflowBranchUtil.<init>(GitflowBranchUtil.java:37)
        at gitflow.ui.GitflowTaskDialogPanelProvider.getOpenTaskPanel(GitflowTaskDialogPanelProvider.java:21)
        at com.intellij.tasks.ui.TaskDialogPanelProvider.lambda$getOpenTaskPanels$0(TaskDialogPanelProvider.java:39)
        at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1888)
        at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1837)
        at com.intellij.tasks.ui.TaskDialogPanelProvider.getOpenTaskPanels(TaskDialogPanelProvider.java:38)
        at com.intellij.tasks.actions.OpenTaskDialog.<init>(OpenTaskDialog.java:103)
        at com.intellij.tasks.actions.GotoTaskAction.lambda$showOpenTaskDialog$0(GotoTaskAction.java:113)
        at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

If I disable GitFlow plugin everything works as expected.

Now, what I find strange about this is that the open project is not stored in a Git repository. It is a HG repository. So GitFlow plugin shouldn't even be active or interfere with anything.

**Comment by OpherV** [comment]
Thanks for the heads up @ragol. Looks like this is an issue with the new task integration feature I added in the last version. I think I know what's the cause but I don't work with Mercurial so I'm not sure how to reproduce in order to test.

Can you please let me know how can I reproduce this on a new project so that I may fix and test?

**Comment by ragol** [comment]
I am not really sure what you really need in order to reproduce the issue. I guess Mercurial should not be necessary. It probably should *not* be a Git repository, so that you'll get `null` for `repo` in [GitflowBranchUtil constructor](https://github.com/OpherV/gitflow4idea/blob/develop/src/gitflow/GitflowBranchUtil.java#L35) (see stack trace above).

It's a guess, but I think the following could suffice:

1. Configure a Task Server (I have Jira, but cannot say if it's important)
1. Open a new task.

As mentioned in the issue description some tasks result in an exception (Jira "stories", tasks without icons), while others don't (Jira "technical sub-tasks", tasks with an icon). I cannot tell whether the icon thing is important, but it is reproducible on my machine.

**Comment by OpherV** [comment]
I think this is the same as #126 , and I just commited a fix
