### ISSUE TITLE
Unable to start new feature. Glitches in the dialog

### ISSUE THREAD

**Issue by optisamit** [OpherV/gitflow4idea#138]
Android studio 2.3 stable.
After updating the plugin to 0.5.1, I cannot start new feature. When trying to enter feature name, the input box does not display entered text correctly. And when exiting the dialog via 'Esc' button, exception occurs

**Comment by OpherV** [comment]
Thanks for the report.
Can you please paste a screenshot of the glitch and a stack trace of the exception?

**Comment by optisamit** [comment]
@OpherV Here you are!
![screenshot_2017-03-28_11-59-32](https://cloud.githubusercontent.com/assets/10066131/24397181/27ab954c-13ae-11e7-9003-3d62a68ce4cc.png)
[stacktrace.txt](https://github.com/OpherV/gitflow4idea/files/875047/stacktrace.txt)

**Comment by OpherV** [comment]
Thanks - btw what feature name were you trying to enter?

**Comment by OpherV** [comment]
In the meantime you can use the previous build until I get this fixed:
https://github.com/OpherV/gitflow4idea/releases/tag/0.5

**Comment by optisamit** [comment]
@OpherV I entered random characters in this case, but it is the same regardless of whether it is just lowercase, digits or something else

**Comment by ablenesi** [comment]
Same here too unfortunately.

**Comment by jarledb** [comment]
Same here, looks like the text is put in backwards e.g. enter "abc" then press the tab or end key; "cba" is displayed. Pasting a string seems to work, but it will not show up untill you press "end" or "tab"

**Comment by AlteaDown** [comment]
Stack trace for the problem: 
```
tried to access method com.intellij.openapi.ui.DialogWrapper.setOKActionEnabled(Z)V from class gitflow.ui.AbstractBranchStartDialog$1
java.lang.IllegalAccessError: tried to access method com.intellij.openapi.ui.DialogWrapper.setOKActionEnabled(Z)V from class gitflow.ui.AbstractBranchStartDialog$1
	at gitflow.ui.AbstractBranchStartDialog$1.validateBranchName(AbstractBranchStartDialog.java:65)
	at gitflow.ui.AbstractBranchStartDialog$1.insertUpdate(AbstractBranchStartDialog.java:50)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1328)
	at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:610)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:455)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
	at gitflow.actions.StartFeatureAction.actionPerformed(StartFeatureAction.java:29)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:875)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.lambda$onChosen$0(PopupFactoryImpl.java:863)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.ui.popup.AbstractPopup.lambda$null$7(AbstractPopup.java:1390)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by safi-manar** [comment]
Hi @OpherV,
My team would love to use this plugin for our project, but we're running into this issue as well. We're using Android Studio 2.3 with gitflow4idea 0.51, and getting the same stack trace that has been posted above.
It seems to me like the edits done to `AbstractBranchStartDialog.validateBranchName()`, where `AbstractBranchStartDialog.this.setOKActionEnabled()` is called works for IntelliJ, but not for Android Studio.
If you're too busy to develop a fix, if you could just point me in the right direction, I could try to get around to a pull request!

**Comment by OpherV** [comment]
@safi-manar 
If you wish to contribute - there's a handy guide to getting started here:
https://github.com/OpherV/gitflow4idea/blob/develop/docs/project_setup.md

To point out the direction - the issue at hand here is a result of the fact Android Studio uses a really old build of IntellIJ, and in newer builds the interface to DialogWrapper was changed. 

Do you know look into whether AS are planning to update anytime soon? 

If not then the solution means something like checking which intelliJ build is available and choosing which interface to use in runtime based on that.

**Comment by akaryakina** [comment]
Guys, there may be an easy fix to this one. Have you just tried to do `AbstractBranchStartDialog.super.setOKActionEnabled()` instead? 
We've just fixed a similar issue in our product.

**Comment by OpherV** [comment]
@akaryakina Thanks for this! I'll merge and hopefully this sorts things out for our dear Android Studio users :)
