### ISSUE TITLE
NoClassDefFoundError: PopupElementWithAdditionalInfo

### ISSUE THREAD

**Issue by xvarlez** [OpherV/gitflow4idea#148]
Hi, 

Just updated to version 0.6.1 and I get the following error when the IDE starts. Results in the Gitflow menu not even being displayed.

```
com/intellij/dvcs/ui/PopupElementWithAdditionalInfo
java.lang.NoClassDefFoundError: com/intellij/dvcs/ui/PopupElementWithAdditionalInfo
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:272)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:268)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:237)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:119)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:73)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at gitflow.actions.GitflowPopupGroup.createActionGroup(GitflowPopupGroup.java:47)
	at gitflow.actions.GitflowPopupGroup.<init>(GitflowPopupGroup.java:36)
	at gitflow.ui.GitflowWidget.update(GitflowWidget.java:165)
	at gitflow.ui.GitflowWidget.access$100(GitflowWidget.java:54)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:143)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.dvcs.ui.PopupElementWithAdditionalInfo PluginClassLoader[Gitflow, 0.6.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
```

My environment is:
```
Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by OpherV** [comment]
Oh bummer. Looks like Android Studio is based off a really old IntelliJ build (162) that didn't have this class. This means that gitflow4idea wrongly advertises itself as supporting 162. 

My suggestion for you until I sort this in the plugin registry is to revert to the previous version

**Comment by optisamit** [comment]
I have the same issue

**Comment by DavidHulsmanNL** [comment]
For those who have no idea how to revert the version:

1. Uninstall the plugin
2. Download the older version from here: https://plugins.jetbrains.com/plugin/7315-git-flow-integration
3. Install the plugin from disk

PS: I have the same problem in PyCharm

**Comment by OpherV** [comment]
Sorry about this guys/gals - I've updated the Jetbrains registry so that if you remove the plugin and reinstall you get the version before this update and it won't break for you.

Unfortunately this also means that until Pycharm, Android studio and any other IntelliJ based product upgrade to the 171 and up builds you won't be able to use the new features, but there's not much I can do about that...

**Comment by OpherV** [comment]
@DavidHulsmanNL Looks likes the latest Pycharm EAPs are based on build 172

**Comment by phunni** [comment]
Trying to downgrade to 0.6.2 by downloading from the link provided above by @DavidHulsmanNL but it simply says 

> Plugin 'Git Flow Integration' is incompatible with this installation

**Comment by OpherV** [comment]
@phunni Try 0.6.1 until I sort it out

**Comment by phunni** [comment]
OK, thanks - will do

**Comment by phunni** [comment]
Intriguingly, I have the same error with 0.6.1:

```
com/intellij/dvcs/ui/PopupElementWithAdditionalInfo
java.lang.NoClassDefFoundError: com/intellij/dvcs/ui/PopupElementWithAdditionalInfo
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:272)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:268)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:237)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:119)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:73)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at gitflow.ui.GitflowWidget.update(GitflowWidget.java:165)
	at gitflow.ui.GitflowWidget.access$100(GitflowWidget.java:54)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:143)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.dvcs.ui.PopupElementWithAdditionalInfo PluginClassLoader[Gitflow, 0.6.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

**Comment by sufish** [comment]
0.5.1 is working

**Comment by peteristhegreat** [comment]
@sufish Thanks for the info.  Can the plugin page get updated to reflect this?  https://plugins.jetbrains.com/plugin/7315-git-flow-integration  Right now it shows that build 162+ of the idea works with v0.6.3, when really it should say 171-173.

**Comment by besi** [comment]
Same crash with RubyMine  2016.3.3

```
RubyMine 2016.3.3
Build #RM-163.15529.6, built on May 22, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
