### ISSUE TITLE
NullPointerException after last update 0.6.1

### ISSUE THREAD

**Issue by RichWeber** [OpherV/gitflow4idea#149]
After the last update 0.6.1 when creating new task (Tools -> Tasks & Context) in IDE PhpStorm 2017.1

```
null
java.lang.NullPointerException
	at gitflow.GitflowConfigUtil.getDevelopBranch(GitflowConfigUtil.java:44)
	at gitflow.ui.GitflowOpenTaskPanel.<init>(GitflowOpenTaskPanel.java:59)
	at gitflow.ui.GitflowTaskDialogPanelProvider.getOpenTaskPanel(GitflowTaskDialogPanelProvider.java:27)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.lambda$getOpenTaskPanels$0(TaskDialogPanelProvider.java:39)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1895)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1844)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.getOpenTaskPanels(TaskDialogPanelProvider.java:38)
	at com.intellij.tasks.actions.OpenTaskDialog.<init>(OpenTaskDialog.java:103)
	at com.intellij.tasks.actions.GotoTaskAction.lambda$showOpenTaskDialog$0(GotoTaskAction.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

<img width="947" alt="2017-06-20 13 19 33" src="https://user-images.githubusercontent.com/1702252/27328559-3504dfe2-55bb-11e7-807e-34998d5adaa7.png">

**Comment by OpherV** [comment]
I must have missed that in the new multi-repo refactor. Thanks for heads up!

**Comment by axute** [comment]
```
null
java.lang.NullPointerException
	at gitflow.ui.AbstractBranchStartDialog.<init>(AbstractBranchStartDialog.java:45)
	at gitflow.ui.GitflowStartFeatureDialog.<init>(GitflowStartFeatureDialog.java:11)
	at gitflow.actions.StartFeatureAction.actionPerformed(StartFeatureAction.java:31)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:968)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:958)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:952)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1396)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
same on create task

**Comment by RichWeber** [comment]
Thanks

**Comment by sebastianhaeni** [comment]
The `NullPointerException` mentioned by @axute still occurs in `AbstractBranchStartDialog:45` as of release `0.6.2`.

**Comment by RichWeber** [comment]
You have to restart IDE or OS

**Comment by RichWeber** [comment]
Maybe it needs not here but I have this error now (0.6.2) while opening new task

```
fatal: Unable to create '/Users/richweber/www/truck-logistic/.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Could not create feature branch 'feature/#7'
Switched to a new branch '#7'
```
