### ISSUE TITLE
NullPointerException when invoking with keyboard shortcut

### ISSUE THREAD

**Issue by pddevins** [OpherV/gitflow4idea#156]
Attempted to assign `Gitflow: Feature Start` to `Ctrl+s, Ctrl+f` as well as switching to `Cmd+F12`, (thinking perhaps it was the secondary keystroke portion that was causing an issue), but will get a NullPointerException when pressing the key combination. Using `Gitflow: Feature Start` through clicking the UI elements works as expected.

**StackTrace**
```
java.lang.NullPointerException
	at gitflow.GitflowConfigUtil.getFeaturePrefix(GitflowConfigUtil.java:58)
	at gitflow.actions.GitflowAction.setup(GitflowAction.java:56)
	at gitflow.actions.GitflowAction.actionPerformed(GitflowAction.java:48)
	at gitflow.actions.StartFeatureAction.actionPerformed(StartFeatureAction.java:29)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by simone86** [comment]
happens the same when pressing alt+shift+n and selecting a task

**Comment by OpherV** [comment]
Thanks for the reports!

**Comment by DavidHulsmanNL** [comment]
I got this error in PyCharm after I switched the Project Interpreter to a virtualenv.

Now I just get a `Error: Not a gitflow-enabled repo yet. Please init git flow` and `Error: Please have a look at the Version Control console for more details`.

When I run `git flow init` in the terminal I get:

C:\Program Files\Git\usr\bin\git-flow: line 47: uname: command not found
C:\Program Files\Git\usr\bin\git-flow: line 76: sed: command not found
C:\Program Files\Git\usr\bin\git-flow: line 76: dirname: command not found
C:\Program Files\Git\usr\bin\git-flow: line 115: /gitflow-shFlags: No such file or directory

Hope this is helpful!

**Comment by OpherV** [comment]
@DavidHulsmanNL If command line git-flow doesn't work then you have an issue with git flow itself - perhaps try to resolve it [there](https://github.com/petervanderdoes/gitflow-avh)?
gitflow4idea is just a front for that command line tool...

also - this is a separate issues than the OP's one with keyboard shortcuts. In the future, for new issues - please open a separate thread

**Comment by DavidHulsmanNL** [comment]
@OpherV I will, thanks! (for the git flow link itself and posting a separate issue in the future :) )
