### ISSUE TITLE
Argument for @NotNull parameter 'project' of git4idea/GitUtil.getRepositoryManager must not be null

### ISSUE THREAD

**Issue by maxmedvedev** [OpherV/gitflow4idea#158]
```
Argument for @NotNull parameter 'project' of git4idea/GitUtil.getRepositoryManager must not be null

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of git4idea/GitUtil.getRepositoryManager must not be null
	at git4idea.GitUtil.getRepositoryManager(GitUtil.java)
	at gitflow.GitflowBranchUtilManager.update(GitflowBranchUtilManager.java:37)
	at gitflow.ui.GitflowWidget.update(GitflowWidget.java:152)
	at gitflow.ui.GitflowWidget.access$100(GitflowWidget.java:54)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:143)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by OpherV** [comment]
Please provide which OS, version of Intellij and build you're using
