### ISSUE TITLE
Exception produce after update to Release 0.6.3

### ISSUE THREAD

**Issue by jmtt89** [OpherV/gitflow4idea#174]
Exception:

```java
com/intellij/dvcs/ui/PopupElementWithAdditionalInfo
java.lang.NoClassDefFoundError: com/intellij/dvcs/ui/PopupElementWithAdditionalInfo
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:272)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:268)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:237)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:119)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:73)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at gitflow.ui.GitflowWidget.update(GitflowWidget.java:165)
	at gitflow.ui.GitflowWidget.access$100(GitflowWidget.java:54)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:143)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.dvcs.ui.PopupElementWithAdditionalInfo PluginClassLoader[Gitflow, 0.6.3]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

the plugin not be loaded after update

**Comment by scb5304** [comment]
+1. Error occurs when launching Android Studio (2.3.3)

**Comment by OpherV** [comment]
I'll look into it.
In the meantime please use the previous version from the [releases page](https://github.com/OpherV/gitflow4idea/releases/tag/0.6.2)

**Comment by jmtt89** [comment]
In Android Studio 3.0 the plugin works!!!

**Comment by OpherV** [comment]
Closing this as builds based on 162 are pretty old
