### ISSUE TITLE
NullPointerException on GitFlow actions with build 181

### ISSUE THREAD

**Issue by kylekatarnls** [OpherV/gitflow4idea#190]
Hi,

Thanks for this great plugin.

When I do Start new release, then enter "v1.2.3", it fails with:
```
null
java.lang.NullPointerException
	at gitflow.GitflowImpl.run(GitflowImpl.java:62)
	at gitflow.GitflowImpl.startRelease(GitflowImpl.java:252)
	at gitflow.actions.StartReleaseAction$1.run(StartReleaseAction.java:35)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I will try to find out what's wrong.

**Comment by kylekatarnls** [comment]
Here is the result of my inspection. When doing
```java
Method m = null;
try {
  m = foo;
} catch (...) {}
```
You must expect m to possibly be null after the try-catch, so you should not call neither m.setAccessible nor m.invoke, both of those call should rather be done in the first try part.

**Comment by OpherV** [comment]
That's more defensive-programming than a fix.
The real question is why in your case the reflection for `GitCommand`'s class `write` method doesn't work and returns null

**Comment by kylekatarnls** [comment]
If the exception should not happen, you should not catch it, if you catch it, you must handle both try and catch cases. And I can't know why the write fails because, the write error is masked by the null pointer exception, if the null exception does not happen, I assume the printStackTrace will be reported.

**Comment by darkman1983** [comment]
I got the same exception on "Init Repo".

**Comment by darkman1983** [comment]
I just tested the "Repo Init" on version 0.6.3 of the plugin with Intellij Idea Community 2017.3.4 and there's an error also.

> Branch name for production releases: [master] 
13:07:23.534: [alpo] git -c core.quotepath=false -c log.showSignature=false flow init
Which branch should be used for bringing forth production releases?
   - dev
   - master
13:07:28.357: master
' does not exist.
Branch name for production releases: [master]

**Comment by OpherV** [comment]
@darkman1983 is the stack trace similar to @kylekatarnls's?

Hmm.. maybe Jetbrains changed something in the git API which causes this break.
What build are you using?

**Comment by kylekatarnls** [comment]
Good track, I just updated Webstorm:
```WebStorm 2018.1
Build #WS-181.4203.535, built on March 22, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0```

**Comment by darkman1983** [comment]
For the same Stacktrace it's:
```
Plugin Version: 0.6.4
IntelliJ IDEA 2018.1 (Community Edition)
Build #IC-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

And for my second comment it's:
```
Plugin Version: 0.6.3
IntelliJ IDEA 2017.3.4 (Community Edition)
Build #IC-173.4548.28, built on January 30, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by pdesterlich** [comment]
I got almost the same exception, the only difference being in that i made a "Start Feature"

```
--- JAVA_EXCEPTION ---
java.lang.NullPointerException
at gitflow.GitflowImpl.run(GitflowImpl.java:62)
at gitflow.GitflowImpl.startFeature(GitflowImpl.java:137)
at gitflow.actions.StartFeatureAction.createFeatureBranch(StartFeatureAction.java:58)
at gitflow.actions.StartFeatureAction.access$000(StartFeatureAction.java:18)
at gitflow.actions.StartFeatureAction$1.run(StartFeatureAction.java:48)
at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

Using GitFlow plugin v0.6.4 on latest Rider

```
JetBrains Rider 2018.1 EAP
Build #RD-181.4035.533, built on March 17, 2018
Rider EAP User
Expiration date: April 16, 2018
JRE: 1.8.0_152-release-1136-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by OpherV** [comment]
Thanks - looking into this.

**Comment by blint587** [comment]
Most probably this is nothing new, but the same thing occurs with Finish Feature:
java.lang.NullPointerException
	at gitflow.GitflowImpl.run(GitflowImpl.java:62)
	at gitflow.GitflowImpl.finishFeature(GitflowImpl.java:172)
	at gitflow.actions.FinishFeatureAction$1.run(FinishFeatureAction.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by OpherV** [comment]
Looks like something got something got broken in 181. This build of Intellij is really unstable in general which makes debugging really hard.

Still looking into it - In the meanwhile I've removed this version of the plugin from the IntelliJ repo

**Comment by nisace** [comment]
FYI, I am having the same issue after updating PyCharm from 2017 to 2018.1.

Thanks for the great plugin

**Comment by OpherV** [comment]
People, it's the same issue. No need to say "me too" - I know. This will happen for certain on all 181 builds.

**Comment by kylekatarnls** [comment]
Why not starting with merging my fix: #191 doesn't seem relevant to you to not call a method on an object you know may be null?

**Comment by OpherV** [comment]
@kylekatarnls, please understand that I'm trying to figure out what is the underlying cause for this null pointer exception, which is probably a result of an interface/implementation change within the IntelliJ code itself. 

That method is the heart of the entire gitflow4idea plugin - it actually performs the git flow command. Without it - there is no plugin.

I don't know what changes will be required to fix the issue as I'm still having issues running 181 in general, but once I do have a fix I will re-evaluate your PR.

**Comment by OpherV** [comment]
@kylekatarnls @darkman1983 @nisace @blint587 @pdesterlich 
Can you please try to install this version locally and see if it still works or if you get errors:

[gitflow4idea_0.6.4.1.jar.zip](https://github.com/OpherV/gitflow4idea/files/1860489/gitflow4idea_0.6.4.1.jar.zip)

**Comment by nisace** [comment]
works for me. thanks!

**Comment by kylekatarnls** [comment]
Start release OK

**Comment by kylekatarnls** [comment]
Note, the try-catches here should still be done in a safer way here IMHO: https://github.com/OpherV/gitflow4idea/commit/71afe4bfe53308f9bf70570a9792b8b66258deb3#diff-56e17d6339468e9112f293730936bca5R30

**Comment by garymc25** [comment]
0.6.4.1 resolved my issue.  Thank you!

**Comment by darkman1983** [comment]
for me it still doesn't work, i can't "Init Repo" now it hangs on:
```
09:59:21.497: [alpo] git -c core.quotepath=false -c log.showSignature=false flow init
Which branch should be used for bringing forth production releases?
   - dev
   - master
```

Nothing happens, it stays at this stage forever.

**Comment by kylekatarnls** [comment]
@darkman1983 I had to uninstall and reinstall, then check for updates to get the last version of the plugin (I assume there is some cache).

**Comment by darkman1983** [comment]
I've replaced the plugin manually. @ C:\Users\Your name\.IdeaIC2018.1\config\plugins

**Comment by tad3j** [comment]
I can confirm 0.6.4.1 solves the issue for me as well (at least with releasing hotfix - will do some more testing and report back if I find anything broken). 

I've only had to manually install via "Install plugin from disk" and it started to work after restart.

**Comment by darkman1983** [comment]
That could be right for start/finish e.g. features, but for the "Init Repo" if no git flow was initialized before, there is an problem.

**Comment by lbottoni** [comment]
gitflow4idea_0.6.4.1 work fine too me. I'm not expert , but can you write on your doc how to create a jar file from your gir rep?

**Comment by OpherV** [comment]
0.6.5 released

**Comment by fifothekid** [comment]
still have the issue even after the update

**Comment by OpherV** [comment]
@fifothekid  Actually I think it's a different issue which I just solved. Please try version 0.6.5.1
@lbottoni Check out the [official Jetbrains guide](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/deploying_plugin.html)

**Comment by IMM0rtalis** [comment]
@OpherV For me it i also not continuing at 

> 11:30:58.065: [porject-name] git -c core.quotepath=false -c log.showSignature=false flow init
Which branch should be used for bringing forth production releases?
>   - master

And the background-task for `initializing repo` keeps running without ending. If I press init again, it just adds another background-task.

Using:
git flow: Version: 0.6.5.1 (first time installed on this machine)
PhpStorm 2018.1.3 EAP
Build #PS-181.4892.94, built on May 2, 2018
JRE: 1.8.0_152-release-1136-b34 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-20-generic
