### ISSUE TITLE
Gitflow init process hangs up

### ISSUE THREAD

**Issue by michal-borek** [OpherV/gitflow4idea#193]
[bug report]

Gitflow > Init hangs up... Your plugin asks me about with popup for certain branches names but then the process hangs up and git flow is not initialized. I need to do `git flow init ` from command line to make your plugin see that the flow is initialized...

I am using latest stable PHPStrorm 2018.1...

PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-38-generic

**Comment by michal-borek** [comment]
`git flow version`

1.10.2 (AVH Edition)

**Comment by OpherV** [comment]
please try version 0.6.5.1

**Comment by jfeid** [comment]
Hi,

Unfortunately, this issue is still there. Gitflow / Init Repo action runs indefinitely.

PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-38-generic

`git flow version`
1.9.1 (AVH Edition)

`Git Flow Integration plugin`
version: 0.6.5.1

**Comment by michal-borek** [comment]
Yep. That is true...

Czw., 12.04.2018, 13:30 użytkownik Ioannis Feidaros <
notifications@github.com> napisał:

**Comment by OpherV** [comment]
@jfeid can you post a log/screenshot of the git version control log?

**Comment by jfeid** [comment]
Just updated PhpStorm to version 2018.1.1 and the issue no longer exists. You can leave it closed :)

**Comment by thasmo** [comment]
Same for me, `Initializing repo` runs forever.

**Comment by Dawen18** [comment]
Stil not working.

PhpStorm 2018.1.6
Build #PS-181.5281.35, built on June 14, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-23-generic

git flow: 1.11.0 (AVH Edition)

fit flow plugin: 0.6.5.1

**Comment by UlrichCech** [comment]
Installed gitflow plugin version 1.0 today, on IntelliJ IDEA 18.2.1 on MacOSX 10.13.6, but the init repo process runs forever. When I quit IntelliJ after minutes of waiting, I get the following in the idea.log:

```
2018-08-08 11:10:59,968 [ 510399]   WARN - ion.process.BaseProcessHandler - Stream closed 
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at com.intellij.execution.process.BaseProcessHandler.closeStreams(BaseProcessHandler.java:100)
	at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:131)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:113)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:120)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:105)
	at com.intellij.execution.process.ProcessWaitFor$1$1.run(ProcessWaitFor.java:65)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-08-08 11:10:59,969 [ 510400]   INFO -  #git4idea.commands.GitHandler - git flow took 178300 ms. Command parameters: 
/usr/local/git/bin/git -c core.quotepath=false -c log.showSignature=false flow init 
2018-08-08 11:10:59,970 [ 510401]   INFO - .changes.ChangeListManagerImpl - Cannot get changes from Git 
com.intellij.openapi.vcs.VcsException: Cannot get changes from Git
	at git4idea.status.GitChangeProvider.getChanges(GitChangeProvider.java:106)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:755)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:668)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$9(ChangeListManagerImpl.java:562)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:561)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$new$0(ChangeListManagerImpl.java:129)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.EmptyProgressIndicator.checkCanceled(EmptyProgressIndicator.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:120)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:208)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.readLock(ReadMostlyRWLock.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl.startRead(ApplicationImpl.java:967)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:957)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:246)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:45)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:42)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at git4idea.util.GitVcsConsoleWriter.getInstance(GitVcsConsoleWriter.java:17)
	at git4idea.commands.GitImplBase.writeOutputToConsole(GitImplBase.java:250)
	at git4idea.commands.GitImplBase.doRun(GitImplBase.java:150)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:119)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:43)
	at git4idea.commands.GitImpl.runCommand(GitImpl.java:54)
	at git4idea.status.GitNewChangesCollector.collectChanges(GitNewChangesCollector.java:106)
	at git4idea.status.GitNewChangesCollector.<init>(GitNewChangesCollector.java:98)
	at git4idea.status.GitNewChangesCollector.collect(GitNewChangesCollector.java:73)
	at git4idea.status.GitChangeProvider.getChanges(GitChangeProvider.java:87)
	... 22 more
```

**Comment by arrgson** [comment]
Still happening in PhpStorm (2018.2.1). Fixed by running in terminal ...
`git -c core.quotepath=false -c log.showSignature=false flow init`
... and restarting PhpStorm.
