### ISSUE TITLE
Can't "Start Feature" in PyCharm 2018.1

### ISSUE THREAD

**Issue by rgoya** [OpherV/gitflow4idea#194]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

Updated the Plugin after updating PyCharm to 2018.1.  When I try to create a feature on a project tjat was working with Gitflow pluglin before, I get the following error:

null
java.lang.NullPointerException
	at gitflow.GitflowImpl.addOptionsCommand(GitflowImpl.java:56)
	at gitflow.GitflowImpl.startFeature(GitflowImpl.java:110)
	at gitflow.actions.StartFeatureAction.createFeatureBranch(StartFeatureAction.java:58)
	at gitflow.actions.StartFeatureAction.access$000(StartFeatureAction.java:18)
	at gitflow.actions.StartFeatureAction$1.run(StartFeatureAction.java:48)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ (PyCharm)
2. Click on "Gitflow" menu bottom right corner of IDE
3. Click on project
4. Click on "Start Feature"
3. 💩 

* **What is the expected behavior?**
Start a feature!

I can "git flow feature start my_new_feature" in a terminal and the plugin correctly detects the feature exists.

* **What is the motivation / use case for changing the behavior?**
Having a working plugin is always a plus!

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.6.5
  - Gitflow version: 0.4.2-pre
  ~~~~
    PyCharm 2018.1 (Professional Edition)
    Build #PY-181.4203.547, built on March 26, 2018
    JRE: 1.8.0_152-release-1136-b20 x86_64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Thanks for the report! I did some refactoring options in the new version and looks like I might have nicked something. I'll look into this

**Comment by OpherV** [comment]
Please try version 0.6.5.1

**Comment by rgoya** [comment]
Works, Thanks.
