### ISSUE TITLE
NullPointerException when creating feature branch

### ISSUE THREAD

**Issue by patric-eberle** [OpherV/gitflow4idea#196]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
When I try to create a feature branch from develop on https://github.com/valantic/vue-template/tree/develop and enter `WF-441_fonts` as a name, I get a NullPointerException. It works when I use the terminal command

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Pull https://github.com/valantic/vue-template/tree/develop
2. Initialize GitFlow
3. Create a new feature from footer menu
4. Use `WF-441_fonts` as feature name
5. Error occurs

```
null
java.lang.NullPointerException
	at gitflow.GitflowImpl.run(GitflowImpl.java:62)
	at gitflow.GitflowImpl.startFeature(GitflowImpl.java:137)
	at gitflow.actions.StartFeatureAction.createFeatureBranch(StartFeatureAction.java:58)
	at gitflow.actions.StartFeatureAction.access$000(StartFeatureAction.java:18)
	at gitflow.actions.StartFeatureAction$1.run(StartFeatureAction.java:48)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

* **What is the expected behavior?**
A new feature branch is created (named `feature/WF-441_fonts`)

* **What is the motivation / use case for changing the behavior?**
-

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.6.4
  - Gitflow version: 1.9.1 (AVH: https://github.com/petervanderdoes/gitflow-avh)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    PhpStorm 2018.1
   Build #PS-181.4203.565, built on March 28, 2018
   Licensed to valantic CEC Schweiz AG / Patric Eberle
   Subscription is active until April 19, 2018
   JRE: 1.8.0_152-release-1136-b20 x86_64
   JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
   macOS 10.13.3
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Hi! Thanks for the report. This bug was fixed in version 0.6.5.1
