### ISSUE TITLE
NullPointerException on gitflow4idea_0.6.41

### ISSUE THREAD

**Issue by bi40** [OpherV/gitflow4idea#203]
Hi,

Thanks for this awesome plugin.

When I'm creating new hotfix, i faced a bug with , it fails bug on gitflow4idea_0.6.41.
Message that i got is :+1: 
java.lang.NullPointerException
	at gitflow.GitflowImpl.run(GitflowImpl.java:62)
	at gitflow.GitflowImpl.startHotfix(GitflowImpl.java:347)
	at gitflow.actions.StartHotfixAction.createHotfixBranch(StartHotfixAction.java:60)
	at gitflow.actions.StartHotfixAction.access$000(StartHotfixAction.java:19)
	at gitflow.actions.StartHotfixAction$1.run(StartHotfixAction.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by OpherV** [comment]
@bi40 can you please try with version 0.6.6 and see if that still happens?
If it does - can you please specify the steps to reproduce
