### ISSUE TITLE
NPE on close task

### ISSUE THREAD

**Issue by andreika63** [OpherV/gitflow4idea#223]
Version: 0.6.5.1

1. Open IntelliJ. I use version IntelliJ IDEA 2018.1.7 (Ultimate Edition)
Build #IU-181.5540.23, built on November 12, 2018)
2. create or open a Task Alt+Shift+N
3. try to close the Task Alt+Shift+W
3. ta da dam....
null
java.lang.NullPointerException
	at gitflow.ui.GitflowCloseTaskPanel.<init>(GitflowCloseTaskPanel.java:64)
	at gitflow.ui.GitflowTaskDialogPanelProvider.getCloseTaskPanel(GitflowTaskDialogPanelProvider.java:41)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.lambda$getCloseTaskPanels$1(TaskDialogPanelProvider.java:44)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1925)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1874)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.getCloseTaskPanels(TaskDialogPanelProvider.java:43)
	at com.intellij.tasks.actions.CloseTaskDialog.<init>(CloseTaskDialog.java:92)
	at com.intellij.tasks.actions.CloseTaskAction.actionPerformed(CloseTaskAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:578)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:627)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:626)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bmwsedee** [comment]
This seems to be fixed with the PR for https://github.com/OpherV/gitflow4idea/issues/235 as well

**Comment by OpherV** [comment]
Version 0.6.9 is now on the Jetbrains Repo
