### ISSUE TITLE
Init repo failed

### ISSUE THREAD

**Issue by kimixu717** [OpherV/gitflow4idea#249]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
init repo failed, it always show "No Gitflow", but acctually succeed, because in sourcetree this repo do not need init again

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open Webstorm
2. GitFlow Actions -> Init repo
3. Notifications shows 'Initialized gitflow in repo xxx', but this plugin still shows No Gitflow

* **What is the expected behavior?**
Init success so I can start  a feature

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.0
  - Gitflow version: 1.12.3(AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    WebStorm 2019.2.2
Build #WS-192.6603.19, built on September 3, 2019
Licensed to xxx
You have a perpetual fallback license for this version
Subscription is active until November 16, 2020
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
GC: ParNew, ConcurrentMarkSweep
Memory: 2008M
Cores: 4
Registry: bigger.font.in.project.view=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, Gitflow
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

java.lang.NullPointerException
	at gitflow.actions.InitRepoAction.update(InitRepoAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:296)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.lambda$getPresentation$0(GotoActionModel.java:645)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$updateOnEdt$4(GotoActionModel.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by OpherV** [comment]
Thanks for the report.
This is a bug in the GUI update logic, in the meantime until this gets sorted out you can simply restart WebStorm after the gitflow init and the plugin widget should work properly

**Comment by kimixu717** [comment]
> Thanks for the report.
> This is a bug in the GUI update logic, in the meantime until this gets sorted out you can simply restart WebStorm after the gitflow init and the plugin widget should work properly

No, restart don't work.
