### ISSUE TITLE
Getting frequent NullPointerExceptions

### ISSUE THREAD

**Issue by vivekmore** [OpherV/gitflow4idea#260]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
I get NPEs quite intermittently (see below)

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Perform Pull (or Fetch) on any branch

* **What is the expected behavior?**
Should not throw NPE

* **What is the motivation / use case for changing the behavior?**
Making the plugin more robust

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *0.7.0*
  - Gitflow version: *1.12.3 (AVH Edition)*

```
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
Licensed to Vivek More
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: compiler.automake.allow.when.app.running=true, ide.tooltip.initialDelay=193
Non-Bundled Plugins: Builder Generator, Lombook Plugin, String Manipulation, VisualVMLauncher, com.denis.zaichenko.angular.2.ws.live.templates, Gitflow, mobi.hsz.idea.gitignore, JRebelPlugin, Karma, de.endrullis.idea.postfixtemplates, com.codota.csp.intellij, com.github.masahirosuzuka.PhoneGapIntelliJPlugin, com.intellij.plugins.html.instantEditing, com.jetbrains.lang.ejs, intellij.prettierJS, MavenRunHelper, org.sonarlint.idea, training, zielu.gittoolbox

```  

* **Other information** 
```
java.lang.NullPointerException
	at gitflow.actions.AbstractStartAction.update(AbstractStartAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:296)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.lambda$getPresentation$0(GotoActionModel.java:645)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$updateOnEdt$4(GotoActionModel.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Keep up the good work!!!**

**Comment by OpherV** [comment]
I can't seem to reproduce this in my testcases, is there perhaps a public repo where this reproduces that I can test it?

I think it's the exact same issue as #232

**Comment by OpherV** [comment]
Closed as duplicate
