### ISSUE TITLE
NPE on isSupportedVersion

### ISSUE THREAD

**Issue by otakupahp** [OpherV/gitflow4idea#272]
* **I'm submitting a ...**
  -bug report

* **What is the current behavior?**

When loading the project I got a IDE Fatal Error. I am using PhpStorm 2019.9.3 updated 22/01/2020

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

Just open a project

* **What is the expected behavior?**
To work

* **What is the motivation / use case for changing the behavior?**

IDE update

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.1
  - Gitflow version: 1.12.3 (AVH Edition)
  
  ~~~~
PhpStorm 2019.3.2
Build #PS-193.6015.48, built on January 22, 2020
Licensed to Giffits / Pablo Hernandez
Subscription is active until February 3, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1910M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: Gitflow, SnakeYAML plugin, YAML/Ansible support, com.chrisrm.idea.MaterialThemeUI, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv 
 ~~~~

** Other info **

I got this log

*****************
java.lang.NullPointerException
	at gitflow.GitflowVersionTester.isSupportedVersion(GitflowVersionTester.java:24)
	at gitflow.GitflowComponent.directoryMappingChanged(GitflowComponent.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:513)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:142)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:438)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:388)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:370)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:241)
	at com.sun.proxy.$Proxy106.mappingChanged(Unknown Source)
	at com.intellij.dvcs.repo.VcsRepositoryManager.checkAndUpdateRepositoriesCollection(VcsRepositoryManager.java:261)
	at com.intellij.dvcs.repo.VcsRepositoryManager.directoryMappingChanged(VcsRepositoryManager.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:513)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:142)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:438)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:388)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:241)
	at com.sun.proxy.$Proxy53.directoryMappingChanged(Unknown Source)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.mappingsChanged(NewMappings.java:366)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.updateMappedRoots(NewMappings.java:201)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.activateActiveVcses(NewMappings.java:122)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.lambda$new$1(NewMappings.java:83)
	at com.intellij.openapi.vcs.impl.VcsInitialization.execute(VcsInitialization.java:92)
	at com.intellij.openapi.vcs.impl.VcsInitialization.access$000(VcsInitialization.java:29)
	at com.intellij.openapi.vcs.impl.VcsInitialization$1.run(VcsInitialization.java:56)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

****************

**Comment by OpherV** [comment]
Can you check if this happens even when you open a project when PHPStorm was just started, with no previously open projects?

**Comment by otakupahp** [comment]
Yes, it also happens in the Welcome screen

![imagen](https://user-images.githubusercontent.com/26227907/72989283-f3ff6080-3dbb-11ea-8075-bc0c023cc5a6.png)

**Comment by OpherV** [comment]
Consolidating all related NPEs to this issue

**Comment by OpherV** [comment]
Did some refactoring, please test with 0.7.2 and reopen if necessary
