### ISSUE TITLE
IntelliJ Ultimate 2019. 3. 3 gitflow null point exception

### ISSUE THREAD

**Issue by joek8901** [OpherV/gitflow4idea#282]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Intellij IDEA 2019. 3.3 (ultimate version)

i just open tasks integrate jira, but occur null point exception

>java.lang.NullPointerException
	at gitflow.ui.GitflowTaskDialogPanelProvider.getOpenTaskPanel(GitflowTaskDialogPanelProvider.java:26)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.getOpenTaskPanel(TaskDialogPanelProvider.java:42)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.lambda$getOpenTaskPanels$0(TaskDialogPanelProvider.java:24)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:2169)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.getOpenTaskPanels(TaskDialogPanelProvider.java:23)
	at com.intellij.tasks.actions.OpenTaskDialog.<init>(OpenTaskDialog.java:96)
	at com.intellij.tasks.actions.GotoTaskAction.lambda$showOpenTaskDialog$0(GotoTaskAction.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

* **What is the expected behavior?**
just tasks open

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
 
  - Gitflow4idea version: 0.7.1
  - Gitflow version: 0.4.1
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Licensed to jiho kim
Subscription is active until March 4, 2021
For educational use only.
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: 
Non-Bundled Plugins: Gitflow, Lombook Plugin, com.atlassian.bitbucket.references, com.nvinayshetty.DTOnator, com.paperetto.dash, org.jetbrains.plugins.vue
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by blundell** [comment]
Update your GitFlow version https://github.com/OpherV/gitflow4idea/blob/develop/GITFLOW_VERSION.md
