### ISSUE TITLE
Do not call synchronous repository update in EDT

### ISSUE THREAD

**Issue by diesl** [OpherV/gitflow4idea#327]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
Rubymine tells me about an IDE Fatal Error

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open Rubymine 
2. Work on feature branch
3. Finish feature
4. Resolve merge conflicts
5. Confirm modal window that merge was successful
6. IDE Fatal Error report

* **What is the expected behavior?**
No IDE Fatal Error report

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.6
  - Gitflow version: 1.11.0 (AVH Edition) 
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    RubyMine 2021.1
    Build #RM-211.6693.118, built on April 6, 2021
    Runtime version: 11.0.10+9-b1341.35 amd64
    VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
  ~~~~

* **Other information** 

Please note: This fatal error occured together with #326 

Stacktrace:
```
java.lang.Throwable: Do not call synchronous repository update in EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForRoot(VcsRepositoryManager.java:182)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForRoot(VcsRepositoryManager.java:172)
	at com.intellij.dvcs.repo.AbstractRepositoryManager.getRepositoryForRoot(AbstractRepositoryManager.java:34)
	at git4idea.GitUtil.getRepositoryForRoot(GitUtil.java:641)
	at git4idea.merge.GitMerger.mergeCommit(GitMerger.java:63)
	at git4idea.merge.GitMerger.mergeCommit(GitMerger.java:55)
	at gitflow.actions.GitflowAction.askUserForMergeSuccess(GitflowAction.java:108)
	at gitflow.actions.GitflowAction.handleMerge(GitflowAction.java:92)
	at gitflow.actions.FinishFeatureAction$1.onSuccess(FinishFeatureAction.java:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:602)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:153)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$6(CoreProgressManager.java:525)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by OpherV** [comment]
Thanks for report. Probably something change in the 211 build of IDEA. I'll look into it.
