### ISSUE TITLE
NPE with IntelliJ version 14.1.3

### ISSUE THREAD

**Issue by mdegols** [OpherV/gitflow4idea#70]
Git flow plugin : 0.4.2
Git: 1.9.4.0.msysgit
IntelliJ version: 14.1.3

Nothing is shown on the status bar below and when I click on the small arrows, I get this exception:

Stacktrace: 
java.lang.NullPointerException
	at gitflow.ui.GitflowWidget.getPopupStep(GitflowWidget.java:106)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl$MultipleTextValuesPresentationWrapper$1.onClick(IdeStatusBarImpl.java:705)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by OpherV** [comment]
What small arrows are you referring to?
 Does this happen on every project?

**Comment by mdegols** [comment]
![gitflow](https://cloud.githubusercontent.com/assets/9446225/7750484/b73d1234-ffd4-11e4-87a2-c24e4ddc5474.jpg)

See the screenshot for the small arrows I'm referring to.
I tried on multiple projects and I have the same issue.
Thanks for your help!

**Comment by OpherV** [comment]
Can you please paste the contents of `.git/config` within your project?
I have a feeling gitflow is not properly configured

**Comment by mdegols** [comment]
This is the current content of the .git/config for one of my projects:

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	hideDotFiles = dotGitOnly
[remote "origin"]
	url = http://vappgithub.data.intra/JavaTeam/IAM-Licensing.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[gitflow "branch"]
	master = master
	develop = develop
[branch "develop"]
	remote = origin
	merge = refs/heads/develop
[gitflow "prefix"]
	feature = feature/
	release = release/
	hotfix = hotfix/
	support = support/
	versiontag = 
[gitflow "path"]
	hooks = c:/dev/Projects/IAM-Licensing/.git/hooks
[gitflow "branch.hotfix/3.1.10"]
	base = master
[gitflow "branch.feature/part66"]
	base = develop
[branch "feature/part66"]
	remote = origin
	merge = refs/heads/feature/part66
[gitflow "branch.feature/documentation"]
	base = develop
[gitflow "branch.feature/Java8"]
	base = develop

**Comment by OpherV** [comment]
I think it's the same issue of #71 
Please check if the new version 0.4.3 solves this and let me know

**Comment by mdegols** [comment]
It was working again on 0.4.2 the last days. I have difficulties to reproduce the behaviour.
I installed the version 0.4.3 and will check if the NPE happens again.
Thanks a lot
