### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Ghost141** [OpherV/gitflow4idea#85]
I got this NullPointerException when I click "OK" button in "Track feature" window.

Here is the error log.

```
null
java.lang.NullPointerException
    at gitflow.ui.GitflowBranchChooseDialog.getSelectedBranchName(GitflowBranchChooseDialog.java:39)
    at gitflow.actions.TrackFeatureAction.actionPerformed(TrackFeatureAction.java:42)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

IDE: PhpStorm 9.0.2
Build verions: PS-141.2462
JRE: 1.8.0_40-release-b90 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OS: Mac OSX 10.10.5

**Comment by throrin19** [comment]
I have the same problem with Webstorm 10.0.4 on Ubuntu 15.04

**Comment by OpherV** [comment]
Does this happen for every project? for every feature branch?

**Comment by throrin19** [comment]
soon as you open the window for creating a feature, hotfix, ... on everyprojects

**Comment by oldspiceland** [comment]
Appear to be having a similar issue when simply creating a new git repository in CLion 1.2.
````
null
java.lang.NullPointerException
	at gitflow.ui.GitflowWidget.update(GitflowWidget.java:168)
	at gitflow.ui.GitflowWidget.access$100(GitflowWidget.java:51)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:144)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
````
Clion 1.2; Git Flow 0.4.6.

**Comment by dvapelnik** [comment]
I have same exception

![ps](https://cloud.githubusercontent.com/assets/1562244/11952220/5735987e-a89f-11e5-8988-9c6fdad7bf6c.png)

Steps to reproduce:

1. Make folder for project
2. Init git from console
3. Make and open project on PhpStorm (do not close PhpStorm)
4. `git flow init` on cosole
5. Switch back to PhpStorm
6. Click on GitFlow panel
7. Catch exception:

```
null
java.lang.NullPointerException
	at java.lang.String.startsWith(String.java:1393)
	at java.lang.String.startsWith(String.java:1422)
	at gitflow.GitflowBranchUtil.isCurrentBranchFeature(GitflowBranchUtil.java:58)
	at gitflow.actions.GitflowActions.getActions(GitflowActions.java:97)
	at gitflow.ui.GitflowWidget.getPopupStep(GitflowWidget.java:113)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl$MultipleTextValuesPresentationWrapper$1.onClick(IdeStatusBarImpl.java:736)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by OpherV** [comment]
@dvapelnik Thanks so much for taking the time to write how to reproduce this!
Now I can finally catch this pesky bug...

**Comment by dvapelnik** [comment]
@OpherV No problem! Thanks for plugin. Do you need more information about the system?

**Comment by biwin** [comment]
happens when enabling vcs system for a new project as well.

**Comment by OpherV** [comment]
For some reason I can't seem to reproduce with @dvapelnik 's instructions anymore. @biwin can you please post how to reproduce?

**Comment by arsounet** [comment]
I've near same error to oldspiceland with Android Studio :
``null
java.lang.NullPointerException
	at gitflow.ui.GitflowWidget.update(GitflowWidget.java:172)
	at gitflow.ui.GitflowWidget.access$100(GitflowWidget.java:52)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:147)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

GitFlow Integration plugin 0.4.7 
Android Studio 2.0, build AI-143.2739321
OS X 10.11.4

**Comment by OpherV** [comment]
Thanks for the stacktrace @arsounet 
This is a tricky one - some sort of weird racing condition in intelliJ's plugin initialisation that I haven't been able to get to the bottom of just yet

**Comment by OpherV** [comment]
This might have been solved - I'm closing in the meantime until someone reopens.
